### ISSUE TITLE
How to use this in vertx-core

### ISSUE THREAD

**Issue by tosheer** [opentracing-contrib/java-vertx-web#13]
Can you please share some example how we can use this? Like how you can integrate it in the most common example in vertx world https://github.com/cescoffier/my-vertx-first-app/tree/post-2

**Comment by pavolloffay** [comment]
Hi, this integration is only for `vertx-web`, `post-2` branch uses only `vertx-core`.

**Comment by tosheer** [comment]
@pavolloffay yes i was in a bit hurry so pasted the wrong branch link can you please check https://github.com/cescoffier/my-vertx-first-app/blob/post-3 specifically https://github.com/cescoffier/my-vertx-first-app/blob/post-3/src/main/java/io/vertx/blog/first/MyFirstVerticle.java. I tried but i am facing issue in getting the tracer from jaeger configuration as that call seems to be blocking the event loop thread. Can you please point me to some example on how can i do it in vertx? or create a small example?

**Comment by tosheer** [comment]
@pavolloffay Any update mate?

**Comment by pavolloffay** [comment]
What specifically is blocking event loop? 

Create the tracer singleton at app init time and supply the tracer to the tracing integration. I can have a look at your code if you want.

**Comment by tosheer** [comment]
@pavolloffay apologies issue was in my code.
