### ISSUE TITLE
how can we inject

### ISSUE THREAD

**Issue by pacman123** [opentracing-contrib/java-vertx-web#14]
Hi,
How can we inject when we are calling downstream service from vertx

**Comment by pavolloffay** [comment]
Hi, 

at the moment it's manual. Here is an example https://github.com/RHsyseng/vertx-msa-ocp/blob/master/Presentation/src/main/java/com/redhat/refarch/vertx/lambdaair/presentation/service/Verticle.java#L272

**Comment by pacman123** [comment]
@pavolloffay  Thanks
