### ISSUE TITLE
Support for Opentracing 0.33.0

### ISSUE THREAD

**Issue by sophokles73** [opentracing-contrib/java-vertx-web#16]
The Tracinghandler currently doesn't work with Opentracing versions < 0.31 because of its usage of the `SpanBuilder.startManual()` method. Are you planning to create a release that supports more recent Opentracing versions?

**Comment by pavolloffay** [comment]
Would you like to submit a PR to update the OT API?

**Comment by sophokles73** [comment]
sure, the changes required are minimal. I was primarily wondering whether you still support this little project and would release a new version once we have the changes in place ;-)
