### ISSUE TITLE
TracingFilter in the Documentation

### ISSUE THREAD

**Issue by Banashri** [opentracing-contrib/java-vertx-web#18]
Hi team,
In the ReadMe file I saw this line
`SpanContext serverContext = TracingFilter.serverSpanContext(routingContext);` 

Could you please tell me where can I get `TracingFilter` ? I was not able to import it from anywhere even after the dependency was included in the project correctly.

Thanks!

**Comment by pavolloffay** [comment]
Hi it should be this: 
https://github.com/opentracing-contrib/java-vertx-web/blob/master/opentracing-vertx-
web/src/main/java/io/opentracing/contrib/vertx/ext/web/TracingHandler.java#L108

I will update the docs.

Thanks for reporting!

**Comment by pavolloffay** [comment]
Actually the readme is correct https://github.com/opentracing-contrib/java-vertx-web#configuration
